/**
 * @file window_desc.h
 * @brief Defines the abstract data structure used to represent a window in DeskUp.
 *
 * This file is part of DeskUp
 *
 * @details
 * The `windowDesc` structure stores all the necessary information about a window
 * so that DeskUp can identify and restore its original state (position, size,
 * and associated executable). It acts as a generic abstraction that can be
 * populated by any backend (e.g., Windows, Linux, macOS).
 *
 * Each backend fills in the fields using its native APIs (for example,
 * `WIN_getAllOpenWindows()` in the Windows implementation).
 *
 * @see windowDesc::saveTo()
 * @see WIN_getAllOpenWindows()
 * @version 0.1.0
 * @date 2025
 * @copyright
 *   Copyright (C) 2025 Nicolas Serrano Garcia
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *   See the GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef WINDOWDESC_H
#define WINDOWDESC_H

#include <string>
#include <filesystem>

namespace fs = std::filesystem;

/**
 * @struct windowDesc
 * @brief Describes a single window instance in the DeskUp system.
 *
 * @details
 * This structure holds all relevant information needed to represent
 * a window in the abstract DeskUp format. It allows storing the
 * executable path, name, and geometry (x, y, width, height).
 *
 * Instances of this struct are typically generated by backend functions such as
 * `WIN_getAllOpenWindows()`, and can later be serialized using `saveTo()`.
 *
 * @see windowDesc::saveTo()
 * @see WIN_getAllOpenWindows()
 */
struct windowDesc {
    /**
     * @brief The window name.
     * @details Usually derived from the executable name or window title.
     */
    std::string name;

    /**
     * @brief The X coordinate (top-left corner) of the window.
     */
    int x;

    /**
     * @brief The Y coordinate (top-left corner) of the window.
     */
    int y;

    /**
     * @brief The window width in pixels.
     */
    int w;

    /**
     * @brief The window height in pixels.
     */
    int h;

    /**
     * @brief The absolute path to the executable that owns this window.
     */
    std::string pathToExec;

    /**
     * @brief Saves the current window description to a file.
     *
     * @details
     * Writes the window’s executable path and geometry (x, y, width, height)
     * to the specified file, each on a new line.  
     *  
     * This function returns a `SaveErrorCode` value to indicate whether the operation
     * succeeded or failed, allowing fine-grained error handling. Positive values
     * indicate success; negative values specify different failure modes.
     *
     * **Format written to file (one value per line):**
     * 1. Path to executable (`pathToExec`)
     * 2. X coordinate
     * 3. Y coordinate
     * 4. Width
     * 5. Height
     *
     * @param path Absolute or relative path to the file where data will be stored.
     * @return One of the following `SaveErrorCode` values:
     *   - `SAVE_SUCCESS` (1): File successfully written.  
     *   - `ERR_EMPTY_PATH` (-1): The path parameter is empty.  
     *   - `ERR_FILE_NOT_OPEN` (-2): File could not be opened.  
     *   - `ERR_NO_PERMISSION` (-3): Insufficient permissions to write the file.  
     *   - `ERR_FILE_NOT_FOUND` (-4): Parent directory missing or invalid path.  
     *   - `ERR_DISK_FULL` (-5): Disk out of space.  
     *   - `ERR_UNKNOWN` (-6): Unexpected write failure.  
     *
     * @note The function performs basic validation and never throws exceptions.
     *       Callers are expected to check the return value and propagate or log
     *       the appropriate error code using `DeskUp::Error::fromSaveError()`.
     *
     * @see windowDesc
     * @see SaveErrorCode
     * @version 0.2.0
     * @date 2025
     */
    int saveTo(fs::path path);

    /**
     * @brief Returns whether the window description is invalid or empty.
     *
     * @details
     * This operator checks if all window geometry attributes (x, y, w, h)
     * are zero, which indicates an uninitialized or invalid state.
     *
     * @return \c true if all coordinates and dimensions are zero, \c false otherwise.
     */
    bool operator!() const {
        return !x && !y && !w && !h;
    }

};

/**
 * @enum SaveErrorCode
 * @brief Enumerates possible results and error codes for `windowDesc::saveTo()`.
 *
 * @details
 * This enumeration defines all return codes used by `windowDesc::saveTo()` to
 * indicate whether the save operation succeeded or failed, and if failed,
 * what type of error occurred.
 *
 * Positive values indicate success; negative values indicate different
 * failure modes, allowing callers (and the backend) to interpret the cause
 * precisely and propagate appropriate `DeskUp::Error` levels.
 *
 * @see windowDesc::saveTo()
 * @version 0.2.1
 * @date 2025
 */
enum SaveErrorCode {
    /**
     * @brief File successfully written.
     * @details Indicates that the window description was saved without issues.
     */
    SAVE_SUCCESS = 1,

    /**
     * @brief The provided file path is empty.
     * @details Returned when `saveTo()` receives an empty path parameter.
     */
    ERR_EMPTY_PATH = -1,

    /**
     * @brief The target file could not be opened.
     * @details The file may not exist or may be locked by another process.
     */
    ERR_FILE_NOT_OPEN = -2,

    /**
     * @brief Insufficient permissions to write the file.
     * @details The current process lacks write access to the target directory.
     */
    ERR_NO_PERMISSION = -3,

    /**
     * @brief File not found or directory path invalid.
     * @details Returned when the parent path of the target file does not exist.
     */
    ERR_FILE_NOT_FOUND = -4,

    /**
     * @brief Disk or storage device is full.
     * @details The save operation could not complete because the disk ran out of space.
     */
    ERR_DISK_FULL = -5,

    /**
     * @brief Unknown or unexpected error during save.
     * @details A generic failure when no specific condition above matches.
     */
    ERR_UNKNOWN = -6
};

#endif