/**
 * @file window_desc.h
 * @brief Defines the abstract data structure used to represent a window in DeskUp.
 *
 * This file is part of DeskUp
 *
 * @details
 * The `windowDesc` structure stores all the necessary information about a window
 * so that DeskUp can identify and restore its original state (position, size,
 * and associated executable). It acts as a generic abstraction that can be
 * populated by any backend (e.g., Windows, Linux, macOS).
 *
 * Each backend fills in the fields using its native APIs (for example,
 * `WIN_getAllOpenWindows()` in the Windows implementation).
 *
 * @see windowDesc::saveTo()
 * @see WIN_getAllOpenWindows()
 * @version 0.1.0
 * @date 2025
 * @copyright
 *   Copyright (C) 2025 Nicolas Serrano Garcia
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *   See the GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef WINDOWDESC_H
#define WINDOWDESC_H

#include <string>
#include <filesystem>

namespace fs = std::filesystem;

/**
 * @struct windowDesc
 * @brief Describes a single window instance in the DeskUp system.
 *
 * @details
 * This structure holds all relevant information needed to represent
 * a window in the abstract DeskUp format. It allows storing the
 * executable path, name, and geometry (x, y, width, height).
 *
 * Instances of this struct are typically generated by backend functions such as
 * `WIN_getAllOpenWindows()`, and can later be serialized using `saveTo()`.
 *
 * @see windowDesc::saveTo()
 * @see WIN_getAllOpenWindows()
 */
struct windowDesc {
    /**
     * @brief The window name.
     * @details Usually derived from the executable name or window title.
     */
    std::string name;

    /**
     * @brief The X coordinate (top-left corner) of the window.
     */
    int x;

    /**
     * @brief The Y coordinate (top-left corner) of the window.
     */
    int y;

    /**
     * @brief The window width in pixels.
     */
    int w;

    /**
     * @brief The window height in pixels.
     */
    int h;

    /**
     * @brief The absolute path to the executable that owns this window.
     */
    std::string pathToExec;

    /**
     * @brief Saves the current window description to a file.
     *
     * @details
     * The function writes the window’s executable path and geometry
     * (x, y, width, height) to the given file, each on a new line.
     *
     * @param path Absolute or relative path to the file where data will be stored.
     * @return 1 if the file was successfully created and written, 0 otherwise.
     *
     * @note The function performs basic validation: it returns 0 if the path is empty
     *       or if the file cannot be opened for writing.
     *
     * @see windowDesc
     */
    int saveTo(fs::path path);

    /**
     * @brief Returns whether the window description is invalid or empty.
     *
     * @details
     * This operator checks if all window geometry attributes (x, y, w, h)
     * are zero, which indicates an uninitialized or invalid state.
     *
     * @return \c true if all coordinates and dimensions are zero, \c false otherwise.
     */
    bool operator!() const {
        return !x && !y && !w && !h;
    }

};

enum SaveErrorCode {
    SAVE_SUCCESS = 1,
    ERR_EMPTY_PATH = -1,
    ERR_FILE_NOT_OPEN = -2,
    ERR_NO_PERMISSION = -3,
    ERR_FILE_NOT_FOUND = -4,
    ERR_DISK_FULL = -5,
    ERR_UNKNOWN = -6
};

#endif